[package]
name = "messaging"
version = "0.1.0"
authors = ["hc-scaffold-framework"]
edition = "2018"

[dependencies]
serde = "=1.0.100"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
serde_derive = "=1.0.100"
hdk = "=0.0.43-alpha3"
hdk_proc_macros = "=0.0.43-alpha3"
holochain_wasm_utils = "=0.0.43-alpha3"
holochain_json_derive = "=0.0.20"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
